# Generated by Django 5.2.17 on 2026-10-05 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='trainee',
            name='college_university',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='trainee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='trainee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='trainee',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='trainee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainee_photos/'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='trainee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_trainee_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
