# Generated by Django 5.2.17 on 2026-10-04 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        ('trainees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='batches.batch')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='trainees.trainee')),
            ],
            options={
                'ordering': ('trainee__user__last_name', 'trainee__user__first_name'),
                'indexes': [models.Index(fields=['batch', 'date'], name='attendance__batch_i_1f764b_idx'), models.Index(fields=['trainee', 'date'], name='attendance__trainee_b04f62_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'trainee', 'date'), name='unique_batch_trainee_attendance_day'), models.CheckConstraint(condition=models.Q(('status__in', ['PRESENT', 'ABSENT', 'LATE', 'EXCUSED'])), name='valid_attendance_status')],
            },
        ),
    ]
