# Generated by Django 5.2.17 on 2026-10-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_cleanup_legacy_table'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='placement',
            new_name='placements__company_c0213d_idx',
            old_name='placements_company_idx',
        ),
        migrations.RenameIndex(
            model_name='placement',
            new_name='placements__status_050fcb_idx',
            old_name='placements_status_idx',
        ),
    ]
