# Generated by Django 5.2.17 on 2026-10-05 13:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_batch_capacity_batch_batch_capacity_positive'),
        ('placements', '0003_rename_placements_company_idx_placements__company_c0213d_idx_and_more'),
        ('trainees', '0003_trainee_verification_status_trainee_verified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=180)),
                ('job_role', models.CharField(max_length=180)),
                ('applied_date', models.DateField(default=django.utils.timezone.localdate)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('ASSESSMENT', 'Assessment'), ('TECHNICAL_ROUND', 'Technical Round'), ('L1_INTERVIEW', 'L1 Interview'), ('L2_INTERVIEW', 'L2 Interview'), ('HR_ROUND', 'HR Round'), ('OFFER_RECEIVED', 'Offer Received'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('JOINED', 'Joined')], db_index=True, default='APPLIED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_applications', to='batches.batch')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='trainees.trainee')),
            ],
            options={
                'ordering': ('-applied_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ApplicationInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('ASSESSMENT_COMPLETED', 'Assessment Completed'), ('SHORTLISTED', 'Shortlisted'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('OFFER_RELEASED', 'Offer Released'), ('JOINED', 'Joined')], db_index=True, default='INTERVIEW_SCHEDULED', max_length=24)),
                ('hr_name', models.CharField(blank=True, max_length=150)),
                ('hr_contact', models.CharField(blank=True, max_length=180)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_application_interviews', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='placements.jobapplication')),
            ],
            options={
                'ordering': ('interview_date', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='WorkflowAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('field_name', models.CharField(max_length=40)),
                ('previous_value', models.CharField(blank=True, max_length=40)),
                ('new_value', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='placements.jobapplication')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_audits', to='trainees.trainee')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='placements.jobapplication')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to=settings.AUTH_USER_MODEL)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to='trainees.trainee')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['batch', 'status'], name='placements__batch_i_e6ee01_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['trainee', 'status'], name='placements__trainee_1a7a23_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationinterview',
            index=models.Index(fields=['status', 'interview_date'], name='placements__status_92c23a_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationinterview',
            index=models.Index(fields=['application', 'status'], name='placements__applica_6f893d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowaudit',
            index=models.Index(fields=['trainee', 'created_at'], name='placements__trainee_5797a9_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowaudit',
            index=models.Index(fields=['entity_type', 'entity_id'], name='placements__entity__6b64bd_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownotification',
            index=models.Index(fields=['recipient', 'read_at', 'created_at'], name='placements__recipie_d47d82_idx'),
        ),
    ]
