# Generated by Django 5.2.17 on 2026-10-04 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('course', models.CharField(db_index=True, max_length=120)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed')], db_index=True, default='UPCOMING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.PROTECT, related_name='training_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_date', 'name'),
                'indexes': [models.Index(fields=['status', 'start_date'], name='batches_bat_status_1a6435_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='batch_end_on_or_after_start')],
            },
        ),
    ]
