# Generated by Django 5.2.17 on 2026-10-05 08:08

import accounts.models
from django.db import migrations, models


def deactivate_removed_role_users(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="TRAINER").update(role="ADMIN", is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(deactivate_removed_role_users, migrations.RunPython.noop),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.TweakTechUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TRAINEE', 'Trainee')], db_index=True, default='TRAINEE', max_length=10),
        ),
    ]
